#!/bin/sh


failure () {
    printf "%s: '%s'\nPlease install it rerun '%s'\n" "${1}" "${*}" "${0}"
    exit 1
}


require () {
    for arg in ${*}; do
        which "${arg}" >/dev/null 2>&1 \
            || failure "REQUIREMENT NOT FOUND" "${arg}"
    done
}


main () {
    require \
        rustc \
        elixirc \
        clang \
        bat \
        make

    {
        make -s clean \
            || failure "ACCESS FAILURE" "CLEAN"

    } && {
        make \
            || failure "CODE FAILURE" "BUILD"

    } && {
        make -s run_all \
            || failure "CODE FAILURE" "RUNTIME PANIC"

    } && \
        return 0
}


main # build and run!
